const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

(async () => {
  const root = path.resolve(__dirname, '..');
  const browser = await chromium.launch({channel: 'chrome', headless: true});
  try {
    const context = await browser.newContext({offline: true, viewport: {width: 1500, height: 1050}});
    const page = await context.newPage();
    const errors = [], externalRequests = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('request', r => { if (/^https?:/.test(r.url())) externalRequests.push(r.url()); });
    await page.goto('file://' + path.join(root, 'index.html'));
    await page.locator('[data-battle-link]').click();
    assert.ok(page.url().endsWith('/battle.html'));
    await page.waitForFunction(() => window.ATLAS_DATA && document.querySelectorAll('#board .cell-coordinate').length === 20);
    assert.equal(await page.evaluate(() => window.ATLAS_DATA.items.length), 100);
    assert.equal(await page.locator('#board .cell-coordinate').count(), 20);
    assert.match(await page.locator('#team-context').innerText(), /己方/);
    await page.locator('#skill-bar .skill-card').first().click();
    assert.match(await page.locator('#detail-content').innerText(), /蓄能/);
    const defaultSkillNames = ['蓄能', '引火', '天火咒', '火中取栗', '乱抓', '元气弹'];
    const cardLabels = await page.locator('#skill-bar .skill-name').allInnerTexts();
    assert.equal(cardLabels.length, defaultSkillNames.length);
    assert.deepEqual(cardLabels, defaultSkillNames);
    await page.locator('#board .unit').first().click();
    assert.ok((await page.locator('#detail-content').innerText()).length > 0);
    await page.locator('#config-btn').click();
    const skills = page.locator('select[data-kind="skill"][data-field="name"]').first();
    const names = await skills.locator('option').evaluateAll(es => es.map(e => e.value));
    const optionLabels = await skills.locator('option').evaluateAll(es => es.map(e => e.textContent.trim()));
    assert.deepEqual(optionLabels, names);
    for (const name of ['雷电牙', '飞抓钩', '上挑']) assert.ok(names.includes(name), name);
    await page.locator('[data-action="config-item-info"]').first().click();
    assert.ok(await page.locator('#config-info-modal').isVisible());
    await page.locator('#close-config-info').click();
    // The battle selector must retain every skill from the merged workbook.
    const sourceNames = await page.evaluate(() => window.ATLAS_DATA.items.filter(i => i.kind === '技能').map(i => i.name));
    assert.ok(sourceNames.every(name => names.includes(name)));
    await page.locator('#cancel-setup').click();
    await page.locator('#board .cell[data-row="2"][data-col="0"]').click();
    const movedPhaseLog = await page.locator('#combat-log').innerText();
    assert.ok(!movedPhaseLog.includes('从 A5 移动到 A3'));
    await page.locator('#step-btn').click();
    assert.ok((await page.locator('#combat-log').innerText()).includes('移动阶段坐标变化'));
    const before = await page.locator('#combat-log').innerText();
    await page.locator('#step-btn').click();
    for (let i = 1; i < 40; i++) await page.locator('#step-btn').click();
    const combatLog = await page.locator('#combat-log').innerText();
    assert.notEqual(combatLog, before);
    assert.match(combatLog, /R\d+ · STEP \d+/);
    assert.match(combatLog, /SKILL|TARGET/);
    assert.ok(defaultSkillNames.some(name => combatLog.includes(name)), 'battle log should retain actual item names');
    assert.ok(await page.locator('#combat-log .log-entry').count() > 0);
    const clawSelection = page.locator('#combat-log .log-entry').filter({hasText: '岩豚 选择技能 利爪'}).last();
    assert.ok(await clawSelection.count() > 0);
    assert.ok(Number(await page.locator('#event-total').innerText()) > 0);
    assert.ok(Number(await page.locator('#round-number').innerText()) > 1);
    assert.ok(await page.locator('#combat-log .log-damage').count() > 0);
    await page.screenshot({path: path.join(root, 'verification/battle-desktop.png'), fullPage: true});
    await page.locator('#reset-btn').click();
    assert.equal(await page.locator('#round-number').innerText(), '1');
    assert.ok(await page.locator('#resolution-banner').isHidden());
    await page.setViewportSize({width: 390, height: 844});
    await page.locator('#config-btn').click();
    assert.ok(await page.locator('#setup-modal').isVisible());
    await page.locator('#cancel-setup').click();
    await page.screenshot({path: path.join(root, 'verification/battle-mobile.png'), fullPage: true});
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    assert.deepEqual(errors, []);
    assert.deepEqual(externalRequests, []);
    const result = {status: 'PASS', checks: ['图谱跳转战斗页', '100 个物品共用数据及全部技能可选', '75 个正式技能均保留物品名', '日志包含回合、结算步、事件与实际物品名', '技能卡和灵宠点击详情', '20 格棋盘（横4×纵5）', '普通移动日志改为结算前坐标汇总', '40 次正式按钮结算并跨回合', '重置', '手机配置及无横向溢出'], pageErrors: errors, externalRequests, scope: '合并兼容性冒烟；不代表全部战斗规则验收'};
    fs.writeFileSync(path.join(root, 'verification/battle-results.json'), JSON.stringify(result, null, 2));
    console.log(result);
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exit(1); });
