// 本地浏览器验收：可通过 PLAYWRIGHT_MODULE 指定现有 Playwright 包。
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
(async () => {
 const browser = await chromium.launch({channel:'chrome',headless:true});
 const page = await browser.newPage({viewport:{width:1500,height:1000}});
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 const failed=[]; page.on('requestfailed',r=>failed.push(r.url()));
 await page.goto('http://127.0.0.1:8765');
 await page.waitForFunction(()=>document.querySelector('#map-transform').style.transform.includes('scale'));
 assert.equal(await page.locator('.map-node').count(),68);
 assert.equal(await page.locator('.item-row').count(),67);
 assert.match(await page.locator('#detail').innerText(),/生命值\s*50/);
 assert.match(await page.locator('#detail').innerText(),/在场存活时我方所有单位获得技能伤害\+2/);
 await page.locator('#search').fill('火球');
 assert.equal(await page.locator('.item-row').count(),1);
 await page.locator('.item-row').click();
 assert.match(await page.locator('#detail').innerText(),/火球/);
 assert.ok(!(await page.locator('#unpin').isHidden()));
 assert.ok(parseInt(await page.locator('#zoom-value').innerText())>100);
 await page.locator('#unpin').click();
 await page.locator('#reset').click();
 const frog=page.locator('[data-node="n1"]');
 await frog.hover();
 await page.locator('#hover-card').waitFor({state:'visible'});
 assert.match(await page.locator('#hover-card').innerText(),/角蛙/);
 assert.match(await page.locator('#detail').innerText(),/回合结束时我方全体技能伤害\+2/);
 await page.locator('#hover-card').hover();
 await page.waitForTimeout(220);
 assert.ok(await page.locator('#hover-card').isVisible());
 await page.keyboard.press('Escape');
 assert.ok(await page.locator('#hover-card').isHidden());
 await page.locator('[data-region="r22"]').click();
 assert.ok(parseInt(await page.locator('#zoom-value').innerText())>100);
 await page.locator('#search').fill('不存在的物品');
 assert.equal(await page.locator('.item-row').count(),0);
 assert.match(await page.locator('#item-list').innerText(),/没有找到/);
 await page.locator('#search').fill('');
 await page.locator('[data-kind="灵兽"]').click();
 assert.equal(await page.locator('.item-row').count(),25);
 await page.locator('[data-kind="技能"]').click();
 assert.equal(await page.locator('.item-row').count(),42);
 await page.locator('[data-kind="全部"]').click();
 await page.locator('#search').fill('钩镰');await page.locator('.item-row').click();
 assert.match(await page.locator('#detail').innerText(),/名称对应待确认/);
 await page.locator('#search').fill('黑犬');await page.getByRole('button',{name:'黑犬，定位并查看详情',exact:true}).click();
 assert.match(await page.locator('#detail').innerText(),/白银 · 最低品质/);
 assert.match(await page.locator('#detail').innerText(),/生命值\s*110/);
 await page.locator('#search').fill('');await page.locator('#reset').click();
 await page.locator('#unpin').click();
 await frog.focus();await page.keyboard.press('Enter');
 assert.match(await page.locator('#detail').innerText(),/已固定/);
 await page.locator('#viewport').focus();await page.keyboard.press('+');
 assert.equal(await page.locator('#zoom-value').innerText(),'125%');
 await page.keyboard.press('0');
 const before=await page.locator('#map-transform').getAttribute('style');
 const box=await page.locator('#viewport').boundingBox();
 await page.mouse.move(box.x+50,box.y+70);await page.mouse.down();await page.mouse.move(box.x+130,box.y+100);await page.mouse.up();
 assert.notEqual(await page.locator('#map-transform').getAttribute('style'),before);
 await page.locator('#reset').click();
 await page.locator('#fullscreen').click();assert.ok(await page.locator('.workspace.expanded').count());
 await page.locator('#fullscreen').click();
 await page.locator('#search').fill('蚁王');await page.getByRole('button',{name:'蚁王，定位并查看详情',exact:true}).click();await page.locator('#search').fill('');await page.locator('#reset').click();
 const out=path.resolve(__dirname,'../verification');fs.mkdirSync(out,{recursive:true});
 await page.screenshot({path:path.join(out,'desktop.png'),fullPage:true});
 await page.locator('[data-region="r22"]').click();await page.screenshot({path:path.join(out,'region-focus.png'),fullPage:true});
 const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
 mobile.on('pageerror',e=>errors.push(e.message));
 await mobile.goto('http://127.0.0.1:8765');
 await mobile.locator('#search').fill('黑犬');await mobile.getByRole('button',{name:'黑犬，定位并查看详情',exact:true}).tap();
 assert.ok(await mobile.locator('#inspector').isVisible());
 assert.match(await mobile.locator('#detail').innerText(),/生命值\s*110/);
 await mobile.screenshot({path:path.join(out,'mobile-detail.png'),fullPage:true});
 await mobile.locator('#close-detail').tap();assert.ok(await mobile.locator('#inspector').isHidden());
 await mobile.locator('#search').fill('');await mobile.locator('#reset').tap();
 assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await mobile.screenshot({path:path.join(out,'mobile.png'),fullPage:true});
 // file:// 验证双击可用，无 fetch/CORS 依赖。
 const local=await browser.newPage();await local.goto('file://'+path.resolve(__dirname,'../index.html'));
 assert.equal(await local.locator('.map-node').count(),68);
 await local.locator('#search').fill('袖箭');await local.getByRole('button',{name:'袖箭，定位并查看详情',exact:true}).click();
 assert.match(await local.locator('#detail').innerText(),/袖箭/);
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);
 const result={status:'PASS',checks:['68 个节点 / 67 个物品','基础数据与白银起始数据','悬停及浮层保持','点击固定与取消','关键词搜索、空结果、分类','名称差异待确认状态','分区聚焦、缩放、拖动、复位','键盘操作','展开与收起','手机详情开关及无横向溢出','file:// 离线打开'],pageErrors:errors,requestFailures:failed};
 fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(result,null,2));console.log(result);
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
