from pathlib import Path
import json
ROOT=Path(__file__).resolve().parent
data=json.loads((ROOT/'三场战斗.json').read_text())
page='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>三套小阵容 · 三场对战日志</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f5ee;color:#304636;font:14px/1.8 -apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif}main{max-width:1100px;margin:auto;padding:34px 25px}h1{font:32px "Songti SC",serif;margin:10px 0}h2{font-size:21px;font-weight:500}.eyebrow{font-size:10px;color:#8a9b7a;letter-spacing:2px}.intro{color:#849578;font-size:12px}.rules{background:#faf5e6;border:1px solid #e6dbc1;border-radius:9px;padding:15px 20px;margin:22px 0;color:#8e7e59;font-size:12px}summary{cursor:pointer}button,select{font:inherit;color:inherit;cursor:pointer}button{border:1px solid #dce4d1;background:#fbfcf7;border-radius:7px;padding:10px 15px}button.active{background:#3b5c44;color:#f5f5e2;border-color:#3b5c44}.tabs{display:flex;gap:10px;margin:22px 0;flex-wrap:wrap}.teams{display:grid;grid-template-columns:1fr 1fr;gap:14px}.team{background:#fffef8;border:1px solid #dce5d2;border-radius:10px;padding:20px}.team h3{font:23px "Songti SC",serif;margin:5px 0 10px}.team small{font-size:10px;color:#91a17e}.team p{font-size:12px;color:#7a9069;margin:5px 0}.stats{display:flex;gap:20px;flex-wrap:wrap;margin-top:15px}.stats span{font-size:11px;color:#8b9b7b}.stats b{display:block;font:23px Georgia,serif;color:#42623a}.result{display:flex;justify-content:space-between;align-items:center;gap:15px;background:#e7efde;border-radius:7px;margin:17px 0;padding:15px 20px;font-size:12px}.result strong{font-size:17px}.filter{display:flex;gap:15px;align-items:center;margin:25px 0 13px;font-size:12px;color:#859975}select{padding:5px 10px;background:#fffef8;border:1px solid #dce4d2;border-radius:5px}.log-entry{background:#fffef9;border:1px solid #e1e7d8;border-radius:7px;padding:13px 17px;margin:8px 0}.log-entry header{font-size:11px;color:#8d9c7d;display:flex;gap:12px;justify-content:space-between}.log-entry strong{font-size:12px;font-weight:500;color:#4b6940}.log-entry p{margin:6px 0;font-size:12px}.delta{background:#f0f5e9;padding:6px 9px;border-radius:4px;color:#6d875b;font-size:11px}.cause{font-size:10px;color:#9ba98b}.round-title{font-size:16px;margin:23px 0 11px;color:#6b825b}footer{margin-top:30px;color:#98a689;font-size:11px}.log-entry.fatal{border-color:#c4927e;background:#fcf4ed}.fatal p{color:#a16850}@media(max-width:650px){main{padding:23px 14px}h1{font-size:26px}.teams{grid-template-columns:1fr}.result{align-items:flex-start;flex-direction:column}.tabs button{font-size:11px;padding:9px}.log-entry header{flex-direction:column;gap:3px}.team{padding:15px}.log-entry{padding:12px}.stats{gap:15px}}
</style><main><span class="eyebrow">COMBAT PROTOTYPE / 三场实际结算记录</span><h1>三套小阵容，互相打一场。</h1><p class="intro">1只灵兽 + 2个技能 / 最低可用品质 / 固定种子 / 按暂定规则实际计算，非预设战斗台词</p><details class="rules"><summary><b>本次模拟的规则与边界</b>：先看这里再比较胜负。三套未按相同品质或成本预算配平。</summary><ol id="rules"></ol></details><div class="tabs" id="tabs"></div><div id="teams" class="teams"></div><div id="result" class="result"></div><div class="filter"><label>查看回合 <select id="round"><option value="all">全部</option></select></label><span id="count"></span></div><section id="logs"></section><footer>每条记录包含回合、阶段、来源、作用对象、效果和状态变化。由于先后手、减伤、触发顺序等采用暂定规则，这三场不能当作正式平衡结论。</footer></main><script>
const D=__DATA__;let index=0;const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const str=v=>typeof v==='object'?JSON.stringify(v):String(v);
$('#rules').innerHTML=D.rules.map(r=>'<li>'+esc(r)+'</li>').join('');
$('#tabs').innerHTML=D.battles.map((b,i)=>`<button data-match="${i}">第${i+1}场 · ${esc(b.teams[0].build)} vs ${esc(b.teams[1].build)}</button>`).join('');
function select(i){index=i;const b=D.battles[i];document.querySelectorAll('[data-match]').forEach(el=>{el.classList.toggle('active',+el.dataset.match===i);el.setAttribute('aria-pressed',String(+el.dataset.match===i));});$('#teams').innerHTML=b.teams.map(t=>`<article class="team"><small>${t.side}方 / ${esc(t.build)}</small><h3>${esc(t.pet)}</h3><p>装备：${t.skills.map(esc).join(' + ')}</p><div class="stats">${['生命','护盾','剧毒','再生','能量'].map(k=>`<span>终局${k}<b>${t.final[k]}</b></span>`).join('')}</div><p>终局技能增伤：${esc(str(t.final.技能增伤))}</p>${Object.keys(t.final.弹药).length?'<p>终局弹药：'+esc(str(t.final.弹药))+'</p>':''}</article>`).join('');$('#result').innerHTML=`<strong>${esc(b.winner)} 获胜</strong><span>${b.rounds} 回合 · ${b.events.length} 条事件 · 随机种子 ${b.seed}</span>`;$('#round').innerHTML='<option value="all">全部回合</option>'+Array.from({length:b.rounds+1},(_,j)=>`<option value="${j}">${j===0?'阵容初始化':'第'+j+'回合'}</option>`).join('');render();}
function render(){const b=D.battles[index],r=$('#round').value;const events=b.events.filter(e=>r==='all'||e.round===+r);$('#count').textContent=events.length+' 条事件';let group='';$('#logs').innerHTML=events.map(e=>{let heading='';const g=e.round+' / '+e.phase;if(group!==g){heading=`<h2 class="round-title">第 ${e.round} 回合 · ${esc(e.phase)}</h2>`;group=g;}const delta=e.before?Object.entries(e.after).filter(([k,v])=>JSON.stringify(v)!==JSON.stringify(e.before[k])).map(([k,v])=>`${k}：${str(e.before[k])} → ${str(v)}`).join('；'):e.after?str(e.after):'';return heading+`<article class="log-entry ${e.effect.includes('立即死亡')?'fatal':''}"><header><span>#${e.seq} · ${e.phase}</span><strong>${esc(e.source)} → ${esc(e.target)}</strong></header><p>${esc(e.effect)}</p>${e.trigger?'<div class="cause">触发：'+esc(e.trigger)+'</div>':''}${delta?'<div class="delta">'+esc(delta)+'</div>':''}</article>`}).join('');}
$('#tabs').onclick=e=>{const b=e.target.closest('[data-match]');if(b)select(+b.dataset.match)};$('#round').onchange=render;select(0);
</script></html>'''
(ROOT/'三场战斗日志.html').write_text(page.replace('__DATA__',json.dumps(data,ensure_ascii=False).replace('</','<\\/')))
print(ROOT/'三场战斗日志.html')
